In [2]:
import tensorflow as tf

In [3]:
hello=tf.constant('Hello TensorFlow')
print(hello)

sess=tf.Session()
result=sess.run(hello)
print(result)
sess.close()

Tensor("Const:0", shape=(), dtype=string)
b'Hello TensorFlow'


#계산그래프만들기

In [4]:
node1=tf.constant(3,tf.float32) #형을 맞춰줘야 계산 가능
node2=tf.constant(4.0)
node3=tf.add(node1,node2)

In [5]:
print("node1: ",node1)
print("node2: ",node2)
print("node3: ",node3)

node1:  Tensor("Const_1:0", shape=(), dtype=float32)
node2:  Tensor("Const_2:0", shape=(), dtype=float32)
node3:  Tensor("Add:0", shape=(), dtype=float32)


In [6]:
session=tf.Session()
print("session.run([node1,node2]): ",session.run([node1,node2]))  #session이 run할떄 실행되는 것
print("session.run(node3): ",session.run(node3))

session.run([node1,node2]):  [3.0, 4.0]
session.run(node3):  7.0


In [7]:
a=tf.constant(1,dtype=tf.float32)
print(a)
print(a.shape)
with tf.Session() as session:
    print(session.run(a))


Tensor("Const_3:0", shape=(), dtype=float32)
()
1.0


#플레이스홀더(Placeholder) : 갈아끼울 수 있다

In [8]:
import tensorflow as tf

input_data=[1,2,3,4,5]
x=tf.placeholder(dtype=tf.float32)
y=x*2

sess=tf.Session()
result=sess.run(y,feed_dict={x:input_data})

print(result)
sess.close()

[ 2.  4.  6.  8. 10.]


In [9]:
x=tf.placeholder(dtype=tf.float32)
x_data=[1,2,4]

#초기값 : tf.random_normal([1,3],stddev=0.35)

weights=tf.Variable([3],dtype=tf.float32)
biases=tf.Variable([4],dtype=tf.float32)

y=weights*x+biases

print("x:",x)
print('weights: ',weights)
print('biases: ',biases)

x: Tensor("Placeholder_1:0", dtype=float32)
weights:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32_ref>
biases:  <tf.Variable 'Variable_1:0' shape=(1,) dtype=float32_ref>


In [10]:
with tf.Session() as session:
    #초기화 오퍼레이션을 실행
    session.run([weights.initializer,biases.initializer]) #initializer무조건 써줘야함
    
    result=session.run(y,feed_dict={x:x_data})
    print(result)
    
    #변수 변경 // 변수 재 할당
    session.run(tf.assign(weights,[2]))
    
    #다시 실행
    result = session.run(y,feed_dict={x:x_data})
    print(result)

[ 7. 10. 16.]
[ 6.  8. 12.]


In [11]:
#변수 초기화 작업 (완전 다 초기화 됨)
init_op = tf.global_variables_initializer()

with tf.Session() as session:
    #초기화 오퍼레이션을 실행
    session.run(init_op)
    
    result=session.run(y,feed_dict={x:x_data})
    print(result)
    
    #변수 변경 // 변수 재 할당
    session.run(tf.assign(weights,[2]))
    
    #다시 실행
    result=session.run(y,feed_dict={x:x_data})
    print(result)

[ 7. 10. 16.]
[ 6.  8. 12.]


Tensor의 속성

In [13]:

a=tf.constant(1) #0차원
b=tf.constant([1,2],dtype=tf.float32) #1차원
c=tf.constant([[1,2],[3,4]],dtype=tf.int32) #2차원, =행렬
d=tf.constant(
[
    [[1.0,2.0],[3,4]],
    [[5,6],[7,8]]
] #3차원
)

print('a:',a)
print('b:',b)
print('c:',c)
print('d:',d)


a: Tensor("Const_8:0", shape=(), dtype=int32)
b: Tensor("Const_9:0", shape=(2,), dtype=float32)
c: Tensor("Const_10:0", shape=(2, 2), dtype=int32)
d: Tensor("Const_11:0", shape=(2, 2, 2), dtype=float32)


rank

In [15]:
print("a's rank:" , a._rank())
print("a's rank:" , b._rank())
print("a's rank:" , c._rank())
print("a's rank:" , d._rank())

print("a's rank:" , tf.rank(a))
print("a's rank:" , tf.rank(b))
print("a's rank:" , tf.rank(c))
print("a's rank:" , tf.rank(d))

a's rank: 0
a's rank: 1
a's rank: 2
a's rank: 3
a's rank: Tensor("Rank_4:0", shape=(), dtype=int32)
a's rank: Tensor("Rank_5:0", shape=(), dtype=int32)
a's rank: Tensor("Rank_6:0", shape=(), dtype=int32)
a's rank: Tensor("Rank_7:0", shape=(), dtype=int32)


Session 관리

In [17]:
session = tf.get_default_session()
print(session)

None


In [19]:
with tf.Session() as sess:
    print(tf.get_default_session())

eval(),initializer.run()

In [25]:
a=tf.constant(2,dtype=tf.float32)
b=tf.Variable(3,dtype=tf.float32)
c=a*b

with tf.Session() as sess:
    print(sess.run(b.initializer))
    print(sess.run(a))
    print(sess.run(c))
    
    ####똑같은 결과
    print(b.initializer.run())
    print(a.eval())
    print(c.eval())

None
2.0
6.0
None
2.0
6.0


* initializer - 따로하거나 global로 진행하거나
* session해주고 거기서 run해줘야 진행함. 
* with에서 쓸 수 있다는건 b.initializer과 같다는 말. = sess.run(b.initializer)
* 디폴트세션은 with절 안에서만 진행하기때문에 initializer을 하면 아무것도 안뜸. get_default_sessionn이 없으면

* sess라는 객체를 만들어서 접근하지 않고 변수에서 바로 접근하기 위해서는(.initializer이나 .eval) with절이나 interactiveSession을 써야한다는 것. 

tf.InteractiveSession

In [26]:
sess=tf.InteractiveSession()
sess.run(b.initializer)
print(a.eval())
print(c.eval())
sess.close()

2.0
6.0


Graph 관리하기
get_default_graph()

In [28]:
tf.get_default_graph()

In [30]:
a=tf.Variable(3)
a.graph is tf.get_default_graph()

True

Graph 객체

In [33]:
graph = tf.Graph()
with graph.as_default():
    b=tf.Variable(2)

In [35]:
a.graph